<?php
/* This file was automatically generated by the `grunt public-cachebuster` command (Mon Dec 10 2018 18:27:04 GMT+0000 (UTC)). */
return array(
	'public/dist/rml_shortcode.js' => '8bb810e739d7c5586963b0af7e09d124',
	'public/dist/rml.js' => 'c25015601c5abe6348b39bba01074008',
	'public/dist/rml.css' => '81b7863be91472e39139ace2deb68977',
	'public/dev/rml_shortcode.js' => 'bfde22476335e10064819599c5c4bd8e',
	'public/dev/rml.js' => 'c30f18a071e51581d451a5b241c2e478',
	'public/dev/rml_shortcode.css' => '9a7cac4970a885476f97fd937b689eff',
	'public/dev/rml.css' => '92c0a229a762bd494db6bd87ddfb4561',
);
